### ISSUE TITLE
server crashing on data download

### ISSUE THREAD

**Issue by r03ert0** [OpenNeuroLab/BrainBox#144]
After the last pull request the server is crashing for some downloads, for example, this one

`http://brainbox.pasteur.fr/mri?url=https://files.osf.io/v1/resources/2c2fx/providers/osfstorage/58e12b78594d9001f992ce15?direct=true&action=download`

This is the error log in the server:

```
No DB entry for MRI: download
Start download:
downloadMRI
78.235.253.198 POST /mri/json 200 141.612 ms - 41
78.235.253.198 GET /img/eyedropper.svg 304 5.936 ms - -
mridb: null
   source: https://files.osf.io/v1/resources/2c2fx/providers/osfstorage/58e12b78594d9001f992ce15?direct=true
     hash: 34390f251b85ff41b692cf93c8a11432
 filename: 58e12b78594d9001f992ce15
     dest: /var/www/html/brainbox/public/data/34390f251b85ff41b692cf93c8a11432/58e12b78594d9001f992ce15
78.235.253.198 GET /img/fill.svg 304 3.611 ms - -
78.235.253.198 GET /img/undo.svg 304 5.262 ms - -
/var/www/html/brainbox/controller/mri/mri.controller.js:95
                newFilename = path.basename(url.parse(fileUrl).path);
                                                      ^

ReferenceError: fileUrl is not defined
    at Request.<anonymous> (/var/www/html/brainbox/controller/mri/mri.controller.js:95:55)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at Request.onRequestResponse (/var/www/html/brainbox/node_modules/request/request.js:954:10)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:425:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
    at TLSSocket.socketOnData (_http_client.js:315:20)
    at emitOne (events.js:77:13)
    at TLSSocket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at TLSSocket.Readable.push (_stream_readable.js:110:10)
    at TLSWrap.onread (net.js:523:20)

npm ERR! Linux 2.6.32-642.15.1.el6.x86_64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v5.4.1
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! brainbox@0.1.0 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the brainbox@0.1.0 start script 'node ./bin/www'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the brainbox package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/www
npm ERR! You can get their info via:
npm ERR!     npm owner ls brainbox
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/html/brainbox/npm-debug.log
SERVER CRASHED WITH CODE 1. RESTARTING
```

**Comment by ntraut** [comment]
I made a new PR but I could not test it because I was not able to download the url link you provided even with my web browser.

**Comment by r03ert0** [comment]
PR accepted. Thanks!
