### ISSUE TITLE
adding a new project broken

### ISSUE THREAD

**Issue by katjaq** [OpenNeuroLab/BrainBox#97]
i can write the name, it checks if it is already taken, it is still happy;
on clicking 'create project' it gives an error and 'freezes' the page
(anyone user doesn't appear as default and no element of the page is responsive)
((
Uncaught SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Object.set [as description] (http://brainbox.dev/js/twoWayBinding.js:45:14)
    at bind2 (http://brainbox.dev/js/twoWayBinding.js:55:13)
    at http://brainbox.dev/project/NIHPD/settings:500:1set @ twoWayBinding.js:45bind2 @ twoWayBinding.js:55(anonymous function) @ settings:500
))

**Comment by r03ert0** [comment]
the bug seems fixed. I'm closing the issue
